In [20]:
import numpy as np
import pandas as pd

In [21]:
dict1 = {
  "name": ['mia', 'maya', 'viktor', 'john'],
  "marks": [92, 34, 82, 97],
  "city": ['paris', 'america', 'NYC','LA']
}

In [22]:
df = pd.DataFrame(dict1)

In [23]:
df

     name  marks     city
0     mia     92    paris
1    maya     34  america
2  viktor     82      NYC
3    john     97       LA

In [24]:
df.to_csv('friends.csv')

👆🏻This will create a excel sheet inside our folder with these details

#### If we do not want any index value :-

In [25]:
df.to_csv(r'C:\Users\Mahima\OneDrive\Documents\Learn-Python-with-Me\Library\friends5.csv', index=False)

In [26]:
df.head(2)

   name  marks     city
0   mia     92    paris
1  maya     34  america

df.tail(3)

In [27]:
df.describe()

           marks
count   4.000000
mean   76.250000
std    28.848743
min    34.000000
25%    70.000000
50%    87.000000
75%    93.250000
max    97.000000

In [28]:
mahima= pd.read_csv('friends.csv')

In [29]:
mahima

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    maya     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [30]:
mahima['name'][1] = 'Tina'

C:\Users\Mahima\AppData\Local\Temp\ipykernel_22192\463834032.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mahima['name'][1] = 'Tina'
C:\Users\Mahima\AppData\Local\Temp\ipykernel_22192\463834032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mahima['name'][1] = 'Tina'

In [31]:
mahima

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    Tina     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [32]:
mahima.index =['a', 'b', 'c', 'd']

In [33]:
mahima

   Unnamed: 0    name  marks     city
a           0     mia     92    paris
b           1    Tina     34  america
c           2  viktor     82      NYC
d           3    john     97       LA

In [34]:
import numpy as np
import pandas as pd 

ser = pd.Series(np.random.rand(49))

In [35]:
ser

0     0.115669
1     0.181646
2     0.230130
3     0.030797
4     0.069649
5     0.755857
6     0.570998
7     0.255923
8     0.608909
9     0.317450
10    0.281182
11    0.766383
12    0.629691
13    0.897869
14    0.396454
15    0.895462
16    0.159463
17    0.902289
18    0.501397
19    0.075100
20    0.863218
21    0.169246
22    0.015052
23    0.876679
24    0.427563
25    0.265047
26    0.784278
27    0.192961
28    0.715580
29    0.725992
30    0.426283
31    0.186916
32    0.914792
33    0.737541
34    0.659557
35    0.535324
36    0.144287
37    0.047397
38    0.735716
39    0.836417
40    0.081423
41    0.730809
42    0.835919
43    0.126868
44    0.308370
45    0.986986
46    0.162940
47    0.534592
48    0.919547
dtype: float64

In [36]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [37]:
newdf

            0         1         2         3         4
0    0.984243  0.404269  0.014587  0.694802  0.508531
1    0.282359  0.613897  0.337520  0.304059  0.949968
2    0.325793  0.220909  0.333247  0.306969  0.735087
3    0.699856  0.847525  0.136097  0.184092  0.439847
4    0.761715  0.914448  0.878245  0.727591  0.515481
..        ...       ...       ...       ...       ...
329  0.995906  0.054723  0.800942  0.136612  0.568263
330  0.501774  0.293933  0.656972  0.853097  0.905336
331  0.379053  0.464100  0.929886  0.550778  0.838877
332  0.438093  0.846144  0.831207  0.652828  0.366912
333  0.481871  0.829889  0.951702  0.887727  0.064623

[334 rows x 5 columns]

In [38]:
type(newdf)

pandas.core.frame.DataFrame

In [39]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.496365    0.495801    0.499241    0.515616    0.502981
std      0.296710    0.282275    0.294245    0.280311    0.280655
min      0.000181    0.006874    0.003017    0.004825    0.001408
25%      0.205219    0.263244    0.249543    0.286021    0.259457
50%      0.503520    0.485522    0.498307    0.525727    0.516565
75%      0.768263    0.745776    0.767508    0.751252    0.735506
max      0.995906    0.989195    0.986608    0.995623    0.995385

In [40]:
mahima.dtypes

Unnamed: 0     int64
name          object
marks          int64
city          object
dtype: object

In [41]:
import pandas as pd

In [42]:
df = pd.read_csv('healthcare_dataset.csv')

In [43]:
df.head(10)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,NaN,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal
5,EMILY JOHNSOn,36,Male,A+,Asthma,2023-12-20,Taylor Newton,Nunez-Humphrey,UnitedHealthcare,48145.110951,389,Urgent,2023-12-24,Ibuprofen,Normal
6,edwArD EDWaRDs,21,Female,AB-,Diabetes,2020-11-03,Kelly Olson,Group Middleton,Medicare,19580.872345,389,Emergency,2020-11-15,Paracetamol,Inconclusive
7,CHrisTInA MARtinez,20,Female,A+,Cancer,2021-12-28,Suzanne Thomas,"Powell Robinson and Valdez,",Cigna,45820.462722,277,Emergency,2022-01-07,Paracetamol,Inconclusive
8,JASmINe aGuIlaR,82,Male,AB+,Asthma,2020-07-01,Daniel Ferguson,Sons Rich and,Cigna,50119.222792,316,Elective,2020-07-14,Aspirin,Abnormal
9,ChRISTopher BerG,58,Female,AB-,Cancer,2021-05-23,Heather Day,Padilla-Walker,UnitedHealthcare,19784.631062,249,Elective,2021-06-22,Paracetamol,Inconclusive

In [44]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [45]:
df.iloc[:,[0]]

                    Name
0          Bobby JacksOn
1           LesLie TErRy
2            DaNnY sMitH
3           andrEw waTtS
4          adrIENNE bEll
...                  ...
55495  eLIZABeTH jaCkSOn
55496         KYle pEREz
55497       HEATher WaNG
55498     JENniFER JOneS
55499       jAMES GARCiA

[55500 rows x 1 columns]

In [46]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            1
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64