In [2]:
import numpy as np
import pandas as pd

In [3]:
dict1 = {
  "name": ['mia', 'maya', 'viktor', 'john'],
  "marks": [92, 34, 82, 97],
  "city": ['paris', 'america', 'NYC','LA']
}

In [4]:
df = pd.DataFrame(dict1)

In [5]:
df

     name  marks     city
0     mia     92    paris
1    maya     34  america
2  viktor     82      NYC
3    john     97       LA

In [6]:
df.to_csv('friends.csv')

👆🏻This will create a excel sheet inside our folder with these details

#### If we do not want any index value :-

In [7]:
df.to_csv(r'C:\Users\Mahima\OneDrive\Documents\Learn-Python-with-Me\Library\friends5.csv', index=False)

In [8]:
df.head(2)

   name  marks     city
0   mia     92    paris
1  maya     34  america

df.tail(3)

In [9]:
df.describe()

           marks
count   4.000000
mean   76.250000
std    28.848743
min    34.000000
25%    70.000000
50%    87.000000
75%    93.250000
max    97.000000

In [10]:
mahima= pd.read_csv('friends.csv')

In [11]:
mahima

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    maya     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [12]:
mahima['name'][1] = 'Tina'

C:\Users\Mahima\AppData\Local\Temp\ipykernel_22048\463834032.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mahima['name'][1] = 'Tina'
C:\Users\Mahima\AppData\Local\Temp\ipykernel_22048\463834032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mahima['name'][1] = 'Tina'

In [13]:
mahima

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    Tina     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [14]:
mahima.index =['a', 'b', 'c', 'd']

In [15]:
mahima

   Unnamed: 0    name  marks     city
a           0     mia     92    paris
b           1    Tina     34  america
c           2  viktor     82      NYC
d           3    john     97       LA

In [16]:
import numpy as np
import pandas as pd 

ser = pd.Series(np.random.rand(49))

In [17]:
ser

0     0.232207
1     0.327609
2     0.070362
3     0.417318
4     0.454512
5     0.330214
6     0.224574
7     0.077401
8     0.153700
9     0.914763
10    0.910452
11    0.747536
12    0.910858
13    0.080069
14    0.144029
15    0.636258
16    0.021223
17    0.579065
18    0.021651
19    0.393073
20    0.535207
21    0.028424
22    0.198735
23    0.788691
24    0.937265
25    0.103075
26    0.130753
27    0.084435
28    0.101902
29    0.877356
30    0.583977
31    0.504079
32    0.788029
33    0.052025
34    0.018481
35    0.644697
36    0.750389
37    0.257109
38    0.142912
39    0.497113
40    0.442548
41    0.333984
42    0.065500
43    0.049433
44    0.669094
45    0.033379
46    0.616392
47    0.026517
48    0.254219
dtype: float64

In [18]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [19]:
newdf

            0         1         2         3         4
0    0.367282  0.153705  0.341927  0.285995  0.415669
1    0.864287  0.750661  0.471176  0.116588  0.339648
2    0.501555  0.766376  0.314724  0.927620  0.708677
3    0.460890  0.689636  0.867429  0.922848  0.840369
4    0.538558  0.087562  0.289607  0.209372  0.291766
..        ...       ...       ...       ...       ...
329  0.629156  0.759699  0.238030  0.146616  0.776989
330  0.409469  0.115364  0.597116  0.276945  0.380472
331  0.263425  0.216670  0.018564  0.078725  0.519132
332  0.763053  0.670486  0.784020  0.034615  0.062194
333  0.514673  0.976506  0.146321  0.697244  0.048259

[334 rows x 5 columns]

In [20]:
type(newdf)

pandas.core.frame.DataFrame

In [21]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.548169    0.496634    0.504015    0.496883    0.523639
std      0.280499    0.294520    0.303056    0.292103    0.290598
min      0.001678    0.003631    0.000715    0.002408    0.002957
25%      0.321852    0.242524    0.246941    0.222490    0.288763
50%      0.561102    0.489314    0.485367    0.493113    0.535033
75%      0.807592    0.759688    0.781664    0.755557    0.762323
max      0.994648    0.997866    0.997281    0.999387    0.995628

In [23]:
mahima.dtypes

Unnamed: 0     int64
name          object
marks          int64
city          object
dtype: object