In [2]:
import numpy as np
import pandas as pd

In [3]:
dict1 = {
  "name": ['mia', 'maya', 'viktor', 'john'],
  "marks": [92, 34, 82, 97],
  "city": ['paris', 'america', 'NYC','LA']
}

In [5]:
df = pd.DataFrame(dict1)

In [6]:
df

     name  marks     city
0     mia     92    paris
1    maya     34  america
2  viktor     82      NYC
3    john     97       LA

In [7]:
df.to_csv('friends.csv')

👆🏻This will create a excel sheet inside our folder with these details

#### If we do not want any index value :-

In [12]:
df.to_csv(r'C:\Users\Mahima\OneDrive\Documents\Learn-Python-with-Me\Library\friends5.csv', index=False)

In [13]:
df.head(2)

   name  marks     city
0   mia     92    paris
1  maya     34  america

df.tail(3)

In [14]:
df.describe()

           marks
count   4.000000
mean   76.250000
std    28.848743
min    34.000000
25%    70.000000
50%    87.000000
75%    93.250000
max    97.000000

In [15]:
mahima= pd.read_csv('friends.csv')

In [16]:
mahima

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    maya     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [17]:
mahima['name'][1] = 'Tina'

C:\Users\Mahima\AppData\Local\Temp\ipykernel_19232\463834032.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  mahima['name'][1] = 'Tina'
C:\Users\Mahima\AppData\Local\Temp\ipykernel_19232\463834032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mahima['name'][1] = 'Tina'

In [18]:
mahima

   Unnamed: 0    name  marks     city
0           0     mia     92    paris
1           1    Tina     34  america
2           2  viktor     82      NYC
3           3    john     97       LA

In [19]:
mahima.index =['a', 'b', 'c', 'd']

In [20]:
mahima

   Unnamed: 0    name  marks     city
a           0     mia     92    paris
b           1    Tina     34  america
c           2  viktor     82      NYC
d           3    john     97       LA

In [4]:
import numpy as np
import pandas as pd 

ser = pd.Series(np.random.rand(49))

In [5]:
ser

0     0.407340
1     0.678354
2     0.560235
3     0.540557
4     0.246665
5     0.513543
6     0.873967
7     0.309946
8     0.090277
9     0.798016
10    0.057308
11    0.102496
12    0.448793
13    0.304709
14    0.818489
15    0.768453
16    0.285882
17    0.980724
18    0.174648
19    0.321409
20    0.798322
21    0.337613
22    0.042592
23    0.639472
24    0.923521
25    0.142178
26    0.999786
27    0.706014
28    0.641284
29    0.524305
30    0.368865
31    0.910820
32    0.942124
33    0.757463
34    0.023231
35    0.023412
36    0.994052
37    0.291552
38    0.657230
39    0.698570
40    0.784578
41    0.944541
42    0.990292
43    0.087053
44    0.813088
45    0.431209
46    0.139058
47    0.982379
48    0.134752
dtype: float64

In [6]:
newdf = pd.DataFrame(np.random.rand(334,5), index=np.arange(334))

In [9]:
newdf

            0         1         2         3         4
0    0.127487  0.782832  0.530493  0.286252  0.190373
1    0.275986  0.596009  0.960348  0.194075  0.608158
2    0.244318  0.606375  0.884071  0.939782  0.037843
3    0.876423  0.074081  0.209215  0.585958  0.039382
4    0.368012  0.866066  0.419982  0.072703  0.067071
..        ...       ...       ...       ...       ...
329  0.841520  0.528649  0.944203  0.596075  0.075422
330  0.463244  0.926480  0.101038  0.659761  0.025477
331  0.908603  0.988000  0.548082  0.527491  0.587805
332  0.081948  0.441466  0.953464  0.254914  0.989524
333  0.515059  0.948627  0.895118  0.553503  0.359745

[334 rows x 5 columns]

In [10]:
type(newdf)

pandas.core.frame.DataFrame

In [11]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.511261    0.508084    0.486484    0.476186    0.482022
std      0.292330    0.284501    0.286280    0.275567    0.305706
min      0.003727    0.005359    0.001239    0.000704    0.002857
25%      0.248889    0.270608    0.241594    0.238341    0.202902
50%      0.526677    0.487764    0.478370    0.484123    0.477641
75%      0.763396    0.762108    0.736422    0.696161    0.750545
max      0.999356    0.994256    0.998791    0.997115    0.999019